import { PropsModel } from '../types'

export const ModelBusiness: PropsModel = {
    name: 'Empresa',
    endpoint: 'business',
    tabs: [
        { id: 1, name: 'Dados Básicos' },
        { id: 2, name: 'Empresarial' },
    ],
    values: [
        {
            id: 1,
            idTab: 1,
            width: '2rem',
            name: 'Código',
            column: 'id',
            atributes: { disabled: true },
            type: 'number',
            values: '',
        },
        {
            id: 2,
            idTab: 1,
            width: '20rem',
            name: 'Razão Social',
            column: 'nameBusiness',
            atributes: { disabled: false },
            type: 'text',
            values: '',
        },
        {
            id: 3,
            idTab: 1,
            width: '10rem',
            name: 'Nome Fantasia',
            column: 'nameFantasia',
            atributes: { disabled: false },
            type: 'text',
            values: '',
        },
        {
            id: 4,
            idTab: 1,
            width: '5rem',
            name: 'CPF/CNPJ',
            column: 'CPF_CNPJ',
            atributes: { disabled: false },
            type: 'text',
            values: '',
        },
        {
            id: 5,
            idTab: 1,
            width: '4rem',
            name: 'E-mail',
            column: 'email',
            atributes: { disabled: false },
            type: 'email',
            values: '',
        },
        {
            id: 6,
            idTab: 1,
            width: '4rem',
            name: 'Inscrição Estadual',
            column: 'IE',
            atributes: { disabled: false },
            type: 'text',
            values: '',
        },
        {
            id: 7,
            idTab: 1,
            width: '4rem',
            name: 'Inscrição Municipal',
            column: 'IMun',
            atributes: { disabled: false },
            type: 'text',
            values: '',
        },
        {
            id: 8,
            width: '4rem',
            idTab: 1,
            name: 'CEP',
            column: 'CEP',
            atributes: { disabled: false },
            type: 'text',
            values: '',
        },
        {
            id: 91,
            idTab: 1,
            width: '4rem',
            name: 'Endereço',
            column: 'address1',
            atributes: { disabled: false },
            type: 'text',
            values: '',
        },
        {
            id: 93,
            idTab: 1,
            width: '4rem',
            name: 'Enddsfereço',
            column: 'address2',
            atributes: { disabled: false },
            type: 'text',
            values: '',
        },
        {
            id: 945,
            idTab: 1,
            width: '4rem',
            name: 'Endedsfreço',
            column: 'address3',
            atributes: { disabled: false },
            type: 'text',
            values: '',
        },
        {
            id: 952,
            idTab: 1,
            width: '4rem',
            name: 'Enderdfeço',
            column: 'address4',
            atributes: { disabled: false },
            type: 'text',
            values: '',
        },
        {
            id: 933,
            idTab: 1,
            width: '4rem',
            name: 'Enderaeço',
            column: 'address5',
            atributes: { disabled: false },
            type: 'text',
            values: '',
        },
    ],
}
